# Generated by Django 5.2.7 on 2026-05-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id_alter_cartitem_id'),
        ('cart', '0002_cart_auth_user'),
    ]

    operations = [
    ]
